- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: import pre-req file
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app_pre_req   

# - name: remove default html file
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: create html  directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: download and unzip the file
#   ansible.builtin.unarchive:
#     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: copy expense source file
  tags:
  - deployment
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx

# - name: restart nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started
